version: "2.1"
services:
  pokemon_service:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1.102
    ports:
    - "6080:6080"
    volumes: 
      - ./src/:/usr/app/
    command: sh -c "cd /usr/app && dotnet run -p PokemonService/PokemonService.csproj"

  # pokemon_testrunner:
  #   image: mcr.microsoft.com/dotnet/core/sdk:3.1.102
  #   volumes: 
  #     - ./src/:/usr/app/
  #   command: sh -c "cd /usr/app && dotnet test"
  #   environment:
  #     - POKEMON_API_HOST=http://localhost:6081
  #     - TRANSLATE_API_HOST=http://localhost:6082
  #     - REDIS_HOST=http://localhost:6379
  #   depends_on:
  #     - mountebank
  #     - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  mountebank:
    image: jkris/mountebank
    ports:
      - "2525:2525"
      - "2526:2526"
      - "6081:6081"
      - "6082:6082"
    restart: always